### ISSUE TITLE
You can get the actual wordlist from his source code

### ISSUE THREAD

**Issue by SeanJA** [billforsternz/wordle#1]
To reduce the size of this file (or it might make it bigger, not sure...).

https://github.com/billforsternz/wordle/blob/b1389eca33359b794432d4ec121c0b93d2e3a90c/wordlist.cpp#L1

![image](https://user-images.githubusercontent.com/102889/148151032-d23c017f-3ad3-4b2d-976a-a8bc99425a9f.png)

**Comment by SeanJA** [comment]
There are 12972 words in the current release of wordle

**Comment by billforsternz** [comment]
Thanks, good work.

**Comment by sidgupta234** [comment]
> There are 12972 words in the current release of wordle

Could you kindly share wordle' repo link?

**Comment by billforsternz** [comment]
I didn't dig down into this, but my assumption is that the game is
implemented client side in JavaScript that you can expose using say the
developer tools in Chrome.

**Comment by billforsternz** [comment]
(Incidentally I heard an interview with Josh Wardle and he said they
reduced 12000 original words to only 5000 common words - again I haven't
dug further to find out whats going on)
